rm nixpacks.toml
cat > nixpacks.toml << 'EOF'
providers = ["python"]

[build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
EOF
cat nixpacks.toml
git add .
git commit -m "Fix corrupted nixpacks.toml file"
git push origin main
