cat > nixpacks.toml << 'EOF'
providers = ["python"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONUNBUFFERED = "1"
EOF
